from funcoes import limpa
limpa()
valor = input('Digite algo: ')
limpa()
print(f'O valor "{valor}", que foi digitado é numerica? \033[34m{valor.isnumeric()}\033[m')
print(f'O valor "{valor}", que foi digitado é alfabética? \033[34m{valor.isalpha()}\033[m')
print(f'O valor "{valor}", que foi digitado é alfanumerica? \033[34m{valor.isalnum()}\033[m')
print(f'O valor "{valor}", que foi digitado é minúscula? \033[34m{valor.islower()}\033[m')
print(f'O valor "{valor}", que foi digitado é maiúsculo? \033[34m{valor.isupper()}\033[m')
print(f'O valor "{valor}", que foi digitado é "printavel"? \033[34m{valor.isprintable()}\033[m\n')
