a = input('Digite algo ')
print("Voce digitou {}, o tipo primitivo de desse valor e ".format(a), type(a))
#print("Voce digitou {}, o tipo primitivo de desse valor e ",type(a).format(a))
#nao aparece o tipo, oq moostar eh o valor da variavel e nao mostra onde esta a mascara {}
print("({}) so tem espacos? ".format(a), a.isspace())
print("({}) so tem numero?".format(a), a.isnumeric())
print("({}) eh alfabetico?".format(a), a.isalpha())
print("({}) eh alfanumerico?".format(a), a.isnumeric())
print("({}) esta em mailsculs?".format(a), a.isupper())
print("({}) esta em minusculas?".format(a), a.islower())
print("({}) esta captalizadas?".format(a), a.istitle())
